// <auto-generated />
using System;
using AdventureLand.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdventureLand.Migrations
{
    [DbContext(typeof(AdventureLandDbContext))]
    partial class AdventureLandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdventureLand.Models.BookingDetails", b =>
                {
                    b.Property<int>("bookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookingId"));

                    b.Property<DateTime?>("bookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bookingId");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("AdventureLand.Models.LandRides", b =>
                {
                    b.Property<int>("landrideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("landrideId"));

                    b.Property<string>("landrideName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rideImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rideStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("landrideId");

                    b.ToTable("LandRides");
                });

            modelBuilder.Entity("AdventureLand.Models.UserRegistration", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("AdventureLand.Models.WaterRides", b =>
                {
                    b.Property<int>("waterRideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("waterRideId"));

                    b.Property<string>("rideImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rideStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("waterRideName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("waterRideId");

                    b.ToTable("WaterRides");
                });
#pragma warning restore 612, 618
        }
    }
}
